# Generated by Django 5.1.1 on 2024-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_productmodel_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
