# Generated by Django 5.1.1 on 2024-10-01 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_purchasemodel_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='date_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
