# Generated by Django 5.1.1 on 2024-10-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_purchasemodel_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.productmodel'),
        ),
    ]
