# Generated by Django 5.1.1 on 2024-09-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SalesProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loss', models.DecimalField(decimal_places=2, max_digits=20)),
                ('damage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('sales', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SalesProduct.salesmodel')),
            ],
        ),
    ]
