# Generated by Django 5.1.1 on 2024-09-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pldmodel',
            name='sales',
        ),
    ]
