# Generated by Django 5.1.1 on 2024-10-02 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0005_alter_purchasemodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('purchase', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.purchasemodel')),
            ],
        ),
    ]
