# Generated by Django 5.1.1 on 2024-10-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpansesAndPayments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='company_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='outstanding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
