# Generated by Django 5.1.1 on 2024-09-29 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('SalesProduct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('return_from', models.CharField(choices=[(1, 'Customer'), (2, 'Ourself')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Product.productmodel')),
                ('return_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
