# Generated by Django 5.1.1 on 2024-09-30 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('SalesProduct', '0002_returnmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnmodel',
            name='return_from',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OURSELF', 'Ourself')], max_length=20),
        ),
        migrations.CreateModel(
            name='DamageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('added_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Product.productmodel')),
            ],
        ),
    ]
